/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador.view;

import compilador.controllers.EditorController;
import java.awt.event.ActionListener;
import javax.swing.UIManager;

/**
 *
 * @author comp2
 */
public class EditorDeTexto extends javax.swing.JFrame {
    ActionListener listener = new EditorController(this);
    
    public EditorDeTexto() {
        initComponents();
    }

    public void setTableModel(Tabela tabela){
        tabelaTokens.setModel(tabela);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTokens = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        buttonNovo = new javax.swing.JButton();
        buttonAbrir = new javax.swing.JButton();
        buttonSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        buttonCompilar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemNovo = new javax.swing.JMenuItem();
        menuItemAbrir = new javax.swing.JMenuItem();
        menuItemSalvar = new javax.swing.JMenuItem();
        menuItemSalvarComo = new javax.swing.JMenuItem();
        menuItemFechar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuItemFormatacao = new javax.swing.JMenuItem();
        menuExecutar = new javax.swing.JMenu();
        menuItemCompilar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTexto.setColumns(20);
        areaDeTexto.setLineWrap(true);
        areaDeTexto.setRows(5);
        areaDeTexto.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaDeTexto);

        tabelaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Lexema"
            }
        ));
        jScrollPane2.setViewportView(tabelaTokens);

        jToolBar1.setRollover(true);

        buttonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador/view/images/novo.png"))); // NOI18N
        buttonNovo.setActionCommand("Novo");
        buttonNovo.setFocusable(false);
        buttonNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonNovo);
        buttonNovo.addActionListener(listener);

        buttonAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador/view/images/abrir.png"))); // NOI18N
        buttonAbrir.setActionCommand("Abrir");
        buttonAbrir.setFocusable(false);
        buttonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonAbrir);
        buttonAbrir.addActionListener(listener);

        buttonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador/view/images/salvar.png"))); // NOI18N
        buttonSalvar.setToolTipText("");
        buttonSalvar.setActionCommand("Salvar");
        buttonSalvar.setFocusable(false);
        buttonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonSalvar);
        buttonSalvar.addActionListener(listener);

        jSeparator1.setToolTipText("");
        jToolBar1.add(jSeparator1);

        buttonCompilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/compilador/view/images/compilar.png"))); // NOI18N
        buttonCompilar.setActionCommand("Compilar");
        buttonCompilar.setFocusable(false);
        buttonCompilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCompilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonCompilar);
        buttonCompilar.addActionListener(listener);

        menuArquivo.setText("Arquivo");

        menuItemNovo.setText("Novo");
        menuItemNovo.addActionListener(listener);
        menuArquivo.add(menuItemNovo);

        menuItemAbrir.setText("Abrir");
        menuItemAbrir.addActionListener(listener);
        menuArquivo.add(menuItemAbrir);

        menuItemSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalvar.setText("Salvar");
        menuItemSalvar.addActionListener(listener);
        menuArquivo.add(menuItemSalvar);

        menuItemSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemSalvarComo.setText("Salvar como");
        menuItemSalvarComo.addActionListener(listener);
        menuArquivo.add(menuItemSalvarComo);

        menuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItemFechar.setText("Sair");
        menuItemFechar.addActionListener(listener);
        menuArquivo.add(menuItemFechar);

        jMenuBar1.add(menuArquivo);

        menuEditar.setText("Editar");

        menuItemFormatacao.setText("Formatação");
        menuItemFormatacao.addActionListener(listener);
        menuEditar.add(menuItemFormatacao);

        jMenuBar1.add(menuEditar);

        menuExecutar.setText("Executar");

        menuItemCompilar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuItemCompilar.setText("Compilar");
        menuItemCompilar.addActionListener(listener);
        menuExecutar.add(menuItemCompilar);

        jMenuBar1.add(menuExecutar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorDeTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditorDeTexto().setVisible(true);
        });
    }

    public String getTexto(){
        return areaDeTexto.getText();
    }

    public void setTexto(String texto){
        areaDeTexto.setText(texto);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDeTexto;
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonCompilar;
    private javax.swing.JButton buttonNovo;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuExecutar;
    private javax.swing.JMenuItem menuItemAbrir;
    private javax.swing.JMenuItem menuItemCompilar;
    private javax.swing.JMenuItem menuItemFechar;
    private javax.swing.JMenuItem menuItemFormatacao;
    private javax.swing.JMenuItem menuItemNovo;
    private javax.swing.JMenuItem menuItemSalvar;
    private javax.swing.JMenuItem menuItemSalvarComo;
    private javax.swing.JTable tabelaTokens;
    // End of variables declaration//GEN-END:variables
}
